version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: phonebook_db
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432"
    volumes:
      - database-data:/var/lib/postgresql/data/

  phonebook:
    image: pups2005/spring-phonebook:latest
    restart: always
    environment:
      DATABASE_URL: db
    ports:
      - "8080:8080"

volumes:
  database-data: